/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>                                                                   
                                                                                              
// Base addresses (from the STM32F411 reference manual)                                     
#define RCC_BASE    0x40023800UL  // Reset and Clock Control                                
#define GPIOA_BASE  0x40020000UL  // GPIO Port A                                            
                                                                                            
// RCC register to enable GPIO clocks                                                       
#define RCC_AHB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x30))                              
                                                                                            
// GPIOA registers                                                                          
#define GPIOA_MODER  (*(volatile uint32_t *)(GPIOA_BASE + 0x00))  // Mode register          
#define GPIOA_ODR    (*(volatile uint32_t *)(GPIOA_BASE + 0x14))  // Output data register 

void delay(uint32_t count) {                                                                
    while (count--) {                                                                       
        __asm__("nop");  // Do nothing, just waste time                                     
    }                                                                                       
}  

int main(void)
{
    // Enable GPIOA clock (bit 0 of AHB1ENR)
    RCC_AHB1ENR |= (1 << 0);

    // Configure PA5 as output
    // MODER register: 2 bits per pin, 00=input, 01=output, 10=alternate, 11=analog
    // PA5 uses bits [11:10], so we set bets 10-11 to 01
    GPIOA_MODER &= ~(3 << 10);  // Clear bits 10-11
    GPIOA_MODER |= (1 << 10);  // Set bit 10 (output mode)

    // Blink forever
    for (;;) {
        GPIOA_ODR ^= (1 << 5);  // Toggle PA5
        delay(500000);  // Wait 
    }
}
